workflows:
  android-release:
    name: Android Release APK (Optimized)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      android_signing:
        - keystore_reference
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build Android Release APK
        script: |
          # Build APK in release mode with obfuscation and split debug info for size optimization
          flutter build apk --release --obfuscate --split-debug-info=build/app/outputs/symbols
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/symbols/*.symbols
    publishing:
      email:
        recipients:
          - user@example.com
